# Copyright 2017 George S. Kong. All rights reserved.
# Use of this source code is governed by a license that can be found in the LICENSE.txt file.

# example secrets file
#
# create separate versions of this file for dev, test, and production instances,
# and set environment variables containing full pathnames to them, named:
# DM_DEV_SECRETS_TOML, DM_TEST_SECRETS_TOML, and DM_PRODUCTION_SECRETS_TOML
#
# the secrets file should always be the last config file read, so it can also
# contain definitions that override definitions in other config files.

adminUser = "user@example.com"                  # user who can perform admin tasks when logged in
adminEmailAddr = "user@example.com"             # receives alerts and contact form submissions

emailServer = "email.example.com"
emailPort = "587"
emailSender = "user@example.com"                # all generated emails have this sender
emailUserName = "---email-username---"
emailPassword = "---email-password---"

metricsUser = "---prometheus-user-name---"      # prometheus uses http basic auth
metricsPassword = "---prometheus-password---"

# for the dev instance, SSL is not enabled:
SSLHosts = [ ]
# for the test and production instances, which should use SSL, use a line similar to the following:
# SSLHosts = [ "example.com", "www.example.com" ]

# for the dev instance, the server runs locally on the development workstation:
baseURL = "http://localhost:8080"
# for the production instance, use a line similar to the following:
# baseURL = "https://example.com"
# to run the test instance on the same server, give it the same domain but a different port:
# baseURL = "https://example.com:8081"

# qsess supports multiple encryption keys, for key rotation.
# keep old ones around for max of all the LongMaxAgeSecs values.
qsessKeys = [ "-----session-encryption-key-----" ]


# you can put local overrides for any other config variables here.
# for example, if the server is behind a reverse proxy that handles TLS, you could add something like:
# 
# TCPAddr = ":8080"
# ReverseProxy = true
# SSL = false
# SSLTCPAddr = ""
# SSLCertDir = ""

